# Generated by Django 5.0.6 on 2024-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsplit',
            old_name='split_amount',
            new_name='user_expense',
        ),
    ]
