# Generated by Django 5.0.6 on 2024-05-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_expense_paymentsplit_user_owes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsplit',
            old_name='user_owes',
            new_name='debtor',
        ),
    ]
