# Generated by Django 5.0.6 on 2024-05-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_owes_paymentsplit_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsplit',
            name='expense',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
    ]
